

import { PlantConfig, BasePlantType, BaseZombieType, LevelConfig, PlantType, ZombieType, LevelScene, ZombieStatConfig, EntityVisuals, AttackDirection, ConsumableType, ProjectileType } from './types';

export const ROWS = 5;
export const COLS = 9;
export const TICK_RATE = 16; // ~60 FPS

export const CELL_WIDTH = 80; 
export const CELL_HEIGHT = 90;
export const MAX_DECK_SIZE = 8;
export const TOTAL_WAVES = 10; // Default fallback

// --- PIXEL ART GENERATOR ---

const PALETTE: Record<string, string> = {
  '.': 'rgba(0,0,0,0)', // Transparent
  'K': '#000000', // Black
  'W': '#FFFFFF', // White
  'G': '#6B7280', // Grey (Iron)
  'R': '#EF4444', // Red
  'O': '#F97316', // Orange
  'Y': '#FACC15', // Yellow
  'L': '#84CC16', // Lime
  'g': '#22C55E', // Green (Plant base)
  'd': '#14532D', // Dark Green (Shadows)
  'T': '#06B6D4', // Teal/Cyan (Ice)
  'B': '#3B82F6', // Blue
  'P': '#9333EA', // Purple
  'M': '#D946EF', // Magenta
  'b': '#7C2D12', // Brown
  'D': '#451a03', // Dark Brown
  'z': '#86EFAC', // Zombie Skin
  'c': '#1E3A8A', // Dark Blue (Clothes)
  's': '#9CA3AF', // Stone/Silver
  'r': '#DC2626', // Dark Red
  'A': '#F472B6', // Pink
};

const generatePixelArt = (ascii: string): string => {
    const canvas = document.createElement('canvas');
    canvas.width = 16;
    canvas.height = 16;
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';
    
    // Clear
    ctx.clearRect(0, 0, 16, 16);

    const rows = ascii.trim().split('\n').map(r => r.trim());
    
    rows.forEach((row, y) => {
        for (let x = 0; x < Math.min(row.length, 16); x++) {
            const char = row[x];
            if (PALETTE[char]) {
                ctx.fillStyle = PALETTE[char];
                ctx.fillRect(x, y, 1, 1);
            }
        }
    });
    
    return canvas.toDataURL('image/png');
};

// --- ASCII TEMPLATES ---

// PLANTS
const ART_SUNFLOWER = [
`.....YOY........
...YYOYOYY......
..YOYOOOYOY.....
..YOOOOOOOY.....
...YYOYOYY......
.....YOY........
......g.........
.....gdg........
....gdgdg.......
...g.gdg.g......
..g..gdg..g.....`,
`.....OYO........
...OYOYOYO......
..OYOOOOOYO.....
..OOOOOOOOO.....
...OYOYOYO......
.....OYO........
......g.........
.....gdg........
....gdgdg.......
...g.gdg.g......
..g..gdg..g.....`
];

const ART_PEASHOOTER = [
`......ggg.......
.....ggggg......
....ggKgg.......
...ggKgg...gg...
...ggggg..gggg..
....ggg...gggg..
.....g.....gg...
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......`,
`.......ggg......
......ggggg.....
.....ggKgg......
....ggKgg...gg..
....ggggg..gggg.
.....ggg...gggg.
......g.....gg..
......g.........
....gdg.........
...g.g.g........
..g..g..g.......`
];

const ART_SNOW_PEA = [
`......BBB.......
.....BBBBB......
....BBKBB.......
...BBKBB...BB...
...BBBBB..BBBB..
....BBB...BBBB..
.....B.....BB...
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......`,
`.......BBB......
......BBBBB.....
.....BBKBB......
....BBKBB...BB..
....BBBBB..BBBB.
.....BBB...BBBB.
......B.....BB..
......g.........
....gdg.........
...g.g.g........
..g..g..g.......`
];

const ART_REPEATER = [
`......ggg.......
.....ggggg......
....ggKggKgg....
...ggKggKgg.....
...gggggggg...g.
....gggggg...gg.
.....g..g...gg..
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......`,
`.......ggg......
......ggggg.....
.....ggKggKgg...
....ggKggKgg....
....gggggggg..g.
.....gggggg..gg.
......g..g..gg..
......g.........
....gdg.........
...g.g.g........
..g..g..g.......`
];

const ART_THREEPEATER = [
`...g..g..g......
..ggg.g.ggg.....
..gKg.g.gKg.....
..ggg.g.ggg.....
...g..g..g......
...g..g..g......
....ggggg.......
.....gdg........
....gdgdg.......
...g.gdg.g......
..g..gdg..g.....`,
`...g..g..g......
..ggg.g.ggg.....
..gKg.g.gKg.....
..ggg.g.ggg.....
...g..g..g......
....ggggg.......
.....gdg........
....gdgdg.......
...g.gdg.g......
..g..gdg..g.....`
];

const ART_GATLING_PEA = [
`......GGG.......
.....GGGGG......
....GGKGG.......
...GGKGG...GG...
...GGGGG..GGGG..
....GGG...GGGG..
.....G.....GG...
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......`,
`......GGG.......
.....GGGGG......
....GGKGG.......
...GGKGG...GG...
...GGGGG..GGGG..
....GGG...GGGG..
.....G.....GG...
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......`
];

const ART_WALLNUT = [
`.....bbb........
...bbbbbbb......
..bbbbbbbbb.....
..bbKbbbKbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
...bbbbbbb......
....bbbbb.......`,
`.....bbb........
...bbbbbbb......
..bbbbbbbbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
...bbbbbbb......
....bbbbb.......`
];

const ART_TALLNUT = [
`.....bbb........
...bbbbbbb......
..bbbbbbbbb.....
..bbKbbbKbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
...bbbbbbb......
....bbbbb.......`,
`.....bbb........
...bbbbbbb......
..bbbbbbbbb.....
..bbKbbbKbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
...bbbbbbb......
....bbbbb.......`
];

const ART_CHERRY_BOMB = [
`.......R.R......
......RR.RR.....
.....RRR.RRR....
.....RRR.RRR....
.....RRR.RRR....
......RR.RR.....
.......R.R......
......gggg......
.....g....g.....`,
`.......R.R......
......RR.RR.....
.....RWR.RWR....
.....RRR.RRR....
.....RRR.RRR....
......RR.RR.....
.......R.R......
......gggg......
.....g....g.....`
];

const ART_POTATO_MINE = [
`................
................
................
................
................
......bbbb......
.....bbbbbb.....
....bbbbbbbb....
.....R....R.....`,
`................
................
................
................
......R..R......
......bbbb......
.....bbbbbb.....
....bbbbbbbb....
.....R....R.....`
];

const ART_CHOMPER = [
`......PPP.......
.....PPPPP......
....PPKPPP......
...PPKKKKP......
...PPPPPPP......
....PPPPP.......
.....P.P........
.....g..........
....gdg.........
...g.gdg.g......
..g..gdg..g.....`,
`.......PPP......
......PPPPP.....
.....PPKPPP.....
....PPKPPKP.....
....PPPPPPP.....
.....PPPPP......
......P.P.......
......g.........
....gdg.........
...g.gdg.g......
..g..gdg..g.....`
];

const ART_PUFF_SHROOM = [
`................
................
................
......PPP.......
.....PPPPP......
....PPPPPPP.....
.....PPPPP......
.......g........
......gdg.......`,
`................
................
................
......PPP.......
.....PPPPP......
....PPPPPPP.....
.....PPPPP......
.......g........
......gdg.......`
];

const ART_SUN_SHROOM = [
`................
................
......YYY.......
.....YYYYY......
....YYYYYYY.....
.....YYYYY......
.......g........
......gdg.......
.....g...g......`,
`................
................
......YYY.......
.....YWYWY......
....YYYYYYY.....
.....YYYYY......
.......g........
......gdg.......
.....g...g......`
];

const ART_FUME_SHROOM = [
`......PPP.......
.....PPPPP......
....PPPPPPP.....
...PPPPPPPPP....
...PPPPPPPPP....
....PPPPPPP.....
.......g........
......gdg.......
.....g...g......`,
`.......PPP......
......PPPPP.....
.....PPPPPPP....
....PPPPPPPPP...
....PPPPPPPPP...
.....PPPPPPP....
.......g........
......gdg.......
.....g...g......`
];

const ART_HYPNO_SHROOM = [
`......MWM.......
.....WMWMW......
....MWMWMWM.....
...WMWMWMWMW....
....MWMWMWM.....
.....WMWMW......
.......g........
......gdg.......
.....g...g......`,
`......WMW.......
.....MWMWM......
....WMWMWMW.....
...MWMWMWMWM....
....WMWMWMW.....
.....MWMWM......
.......g........
......gdg.......
.....g...g......`
];

const ART_SCAREDY_SHROOM = [
`......PPP.......
.....PPPPP......
....PPKPPKP.....
....PPPPPPP.....
.......P........
.......P........
.......P........
.......g........
......gdg.......`,
`................
................
................
................
......PPP.......
.....PPPPP......
.....PPPPP......
.......g........
......gdg.......`
];

const ART_ICE_SHROOM = [
`......TTT.......
.....TTTTT......
....TTTTTTT.....
...TTTTTTTTT....
...TTTTTTTTT....
....TTTTTTT.....
.......B........
......BdB.......
.....B...B......`,
`......WWW.......
.....WWTWW......
....WWTTTWW.....
...WTTTTTTTW....
...WTTTTTTTW....
....WWTTTWW.....
.......B........
......BdB.......
.....B...B......`
];

const ART_DOOM_SHROOM = [
`......KKK.......
.....KKKKK......
....KKKKKKK.....
...KKKKKKKKK....
...KKKKKKKKK....
....KKKKKKK.....
.......K........
......KdK.......
.....K...K......`,
`......KKK.......
.....KRKRK......
....KRKKKRK.....
...KRKKKKKRK....
...KRKKKKKRK....
....KRKKKRK.....
.......K........
......KdK.......
.....K...K......`
];

const ART_GRAVE_BUSTER = [
`...gggggggg.....
..ggKggggKgg....
.gggggggggggg...
.ggKggggggKgg...
..gggggggggg....
...gggggggg.....
....g....g......
...g......g.....`,
`....gggggggg....
...ggKggggKgg...
..gggggggggggg..
..ggKggggggKgg..
...gggggggggg...
....gggggggg....
.....g....g.....
....g......g....`
];

const ART_JALAPENO = [
`......rrr.......
.....rrrrr......
....rrrrrrr.....
....rrKrrrK.....
....rrrrrrr.....
....rrrrrrr.....
.....rrrrr......
......rrr.......
.......g........`,
`......RRR.......
.....RRRRR......
....RRRRRRR.....
....RRKRRRK.....
....RRRRRRR.....
....RRRRRRR.....
.....RRRRR......
......RRR.......
.......g........`
];

const ART_SPIKEWEED = [
`................
................
................
................
................
.G.G.G.G.G.G.G..
GGGGGGGGGGGGGGG.
.G.G.G.G.G.G.G..`,
`................
................
................
................
................
..G.G.G.G.G.G...
.GGGGGGGGGGGGG..
..G.G.G.G.G.G...`
];

const ART_TORCHWOOD = [
`......O.O.......
.....OYOYO......
....OYOOOYO.....
...bbbbbbbbb....
...bbKbbbKbb....
...bbbbbbbbb....
...bbbbbbbbb....
....bbbbbbb.....`,
`.......O........
.....OYOYO......
....OYOOOYO.....
...bbbbbbbbb....
...bbKbbbKbb....
...bbbbbbbbb....
...bbbbbbbbb....
....bbbbbbb.....`
];

const ART_MELON_PULT = [
`........gggg....
.......gggggg...
......gggggggg..
.......gggggg...
..bb....gggg....
.bbbb....gg.....
.bbbb.....g.....
.bbbb....gdg....
..bb....g.g.g...`,
`.........gggg...
........gggggg..
.......gggggggg.
........gggggg..
..bb.....gggg...
.bbbb.....gg....
.bbbb......g....
.bbbb.....gdg...
..bb.....g.g.g..`
];

const ART_KERNEL_PULT = [
`........YYYY....
.......YYYYYY...
......YYYYYYYY..
.......YYYYYY...
..bb....YYYY....
.bbbb....YY.....
.bbbb.....Y.....
.bbbb....gdg....
..bb....g.g.g...`,
`.........YYYY...
........YYYYYY..
.......YYYYYYYY.
........YYYYYY..
..bb.....YYYY...
.bbbb.....YY....
.bbbb......Y....
.bbbb.....gdg...
..bb.....g.g.g..`
];

const ART_COB_CANNON = [
`...YYYYYYYYYY...
..YYYYYYYYYYYY..
.YYYYYYYYYYYYYY.
.YYbbbbbbbbbbYY.
.YYbbbbbbbbbbYY.
.YYYYYYYYYYYYYY.
..YYYYYYYYYYYY..
...YYYYYYYYYY...
....g..gg..g....
...g.g.gg.g.g...`,
`...YYYYYYYYYY...
..YYYYYYYYYYYY..
.YYYYYYYYYYYYYY.
.YYbbbbbbbbbbYY.
.YYbbbbbbbbbbYY.
.YYYYYYYYYYYYYY.
..YYYYYYYYYYYY..
...YYYYYYYYYY...
....g..gg..g....
...g.g.gg.g.g...`
];

const ART_STARFRUIT = [
`.......Y........
......YYY.......
..Y..YYYYY..Y...
.YYY.YYYYY.YYY..
..YYYYYYYYYYY...
...YYYYYYYYY....
....YYYYYYY.....
...YYY...YYY....
..YY.......YY...`,
`.......Y........
......YYY.......
..Y..YYYYY..Y...
.YYY.YYYYY.YYY..
..YYYYYYYYYYY...
...YYYYYYYYY....
....YYYYYYY.....
...YYY...YYY....
..YY.......YY...`
];

const ART_TWIN_SUNFLOWER = [
`...YOY...YOY....
..YOYOY.YOYOY...
..YOOOY.YOOOY...
...YOY...YOY....
......g.g.......
.......g........
......gdg.......
.....gdgdg......
....g.gdg.g.....`,
`...OYO...OYO....
..OYOYO.OYOYO...
..OYOOO.OYOOO...
...OYO...OYO....
......g.g.......
.......g........
......gdg.......
.....gdgdg......
....g.gdg.g.....`
];

const ART_SQUASH = [
`................
.....ggggg......
....ggggggg.....
...ggggggggg....
...ggKgggKgg....
...ggggggggg....
...ggggggggg....
...ggggggggg....
....ggggggg.....
................`,
`................
................
................
...ggKgggKgg....
...ggggggggg....
...ggggggggg....
...ggggggggg....
....ggggggg.....
................`
];

// --- ZOMBIE ARTS ---

const ART_ZOMBIE_WALK = [
`......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
...c.cczzcc.c...
.....cczzcc.....
.....bb..bb.....
....bb....bb....
....K......K....`,
`......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
...c.cczzcc.c...
.....cczzcc.....
.....bb..bb.....
.....bb..bb.....
.....K....K.....`
];

const ART_ZOMBIE_CONE = [
`.......O........
......OOO.......
.....OOOOO......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....`,
`.......O........
......OOO.......
.....OOOOO......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....`
];

const ART_ZOMBIE_BUCKET = [
`......GGG.......
.....GGGGGG.....
.....GGGGGG.....
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....`,
`......GGG.......
.....GGGGGG.....
.....GGGGGG.....
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....`
];

const ART_ZOMBIE_FOOTBALL = [
`......RRR.......
.....RRRRR......
.....zzKzzK.....
......zzzz......
....RRRzzRRR....
...RRRRzzRRRR...
...R.RRzzRR.R...
.....RRzzRR.....
.....bb..bb.....`,
`......RRR.......
.....RRRRR......
.....zzKzzK.....
......zzzz......
....RRRzzRRR....
...RRRRzzRRRR...
...R.RRzzRR.R...
.....RRzzRR.....
.....bb..bb.....`
];

const ART_ZOMBIE_NEWSPAPER = [
`......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
...c.WWWWWW.c...
.....WWWWWW.....
.....bb..bb.....`,
`......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
...c.WWWWWW.c...
.....WWWWWW.....
.....bb..bb.....`
];

const ART_ZOMBIE_SCREEN = [
`......zzzz..G...
.....zzzzzz.G...
.....zzKzzK.G...
......zzzz..G...
....ccczzcc.G...
...cccczzcc.G...
...c.cczzcc.G...
.....cczzcc.G...
.....bb..bb.G...`,
`......zzzz..G...
.....zzzzzz.G...
.....zzKzzK.G...
......zzzz..G...
....ccczzcc.G...
...cccczzcc.G...
...c.cczzcc.G...
.....cczzcc.G...
.....bb..bb.G...`
];

const ART_ZOMBIE_IMP = [
`.....zzzz.......
....zzzzzz......
....zzKzzK......
.....zzzz.......
...ccczzccc.....
..cccczzcccc....
....cczzcc......
....bb..bb......`,
`.....zzzz.......
....zzzzzz......
....zzKzzK......
.....zzzz.......
...ccczzccc.....
..cccczzcccc....
....cczzcc......
....bb..bb......`
];

const ART_ZOMBIE_GARGANTUAR = [
`........zzzz........
.......zzzzzz.......
.......zzKzzK.......
........zzzz........
......ccczzccc......
.....cccczzcccc.....
.....c.cczzcc.c.....
.......cczzcc.......
.......bb..bb.......
.......bb..bb.......`,
`........zzzz........
.......zzzzzz.......
.......zzKzzK........
........zzzz........
......ccczzccc......
.....cccczzcccc.....
.....c.cczzcc.c.....
.......cczzcc.......
.......bb..bb.......
.......bb..bb.......`
];

const ART_POLE_VAULTING_RUN = [
`......R.........
.....RR.........
......zzzz......
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....
....bb....bb....
...K........K...`,
`......R.........
.....RR.........
......zzzz......
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....
.....bb..bb.....
....K......K....`
];

const ART_POLE_VAULTING_JUMP = `
................
......R.........
......zzzz......
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....
....bb....bb....
`;

const ART_DANCING = [
`......zzzz......
...A.zzzzzz.A...
...A.zzKzzK.A...
...A..zzzz..A...
....RRRzzRRR....
...RRRRzzRRRR...
...R.RRzzRR.R...
.....RRzzRR.....
.....WW..WW.....
.....WW..WW.....
....WW....WW....`,
`......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
..A.RRRzzRRR.A..
..ARRRRzzRRRRA..
...R.RRzzRR.R...
.....RRzzRR.....
.....WW..WW.....
....WW....WW....
...WW......WW...`
];

const ART_DANCING_SUMMON = `
......zzzz......
...A.zzzzzz.A...
...A.zzKzzK.A...
...A..zzzz..A...
....RRRzzRRR....
...RRRRzzRRRR...
...R.RRzzRR.R...
.....RRzzRR.....
....WW....WW....
....WW....WW....
...WW......WW...
`;

const ART_BACKUP_DANCER = [
`......zzzz......
.....zzzzzz.....
...A.zzKzzK.A...
......zzzz......
....RRRzzRRR....
...RRRRzzRRRR...
.....RRzzRR.....
.....WW..WW.....
.....WW..WW.....`,
`......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
...ARRRzzRRRA...
...RRRRzzRRRR...
.....RRzzRR.....
....WW....WW....
...WW......WW...`
];

const ART_ZOMBONI = `
................
...RRRRRRRRR....
..RRRRRRRRRRR...
.RRRRzzzzRRRRR..
RRRRzzKzzKRRRRR.
RRRRRzzzzRRRRRR.
RRRRRccccRRRRRR.
.GGGGGGGGGGGGG..
.G.G.G.G.G.G.G..
GGGGGGGGGGGGGGG.
`;


// --- STATS ---

// Helper to create visual config
const createVisuals = (idle: string | string[], attack?: string | string[], fps = 5): EntityVisuals => {
    const idleFrames = Array.isArray(idle) ? idle.map(generatePixelArt) : [generatePixelArt(idle)];
    const attackFrames = attack ? (Array.isArray(attack) ? attack.map(generatePixelArt) : [generatePixelArt(attack)]) : undefined;
    
    return {
        idle: { frames: idleFrames, fps },
        ...(attackFrames ? { attack: { frames: attackFrames, fps } } : {}),
        gridSize: 16
    };
};

// Helper for Zombies
const createZombieVisuals = (idle: string | string[], attack: string | string[], fps = 5, extra?: Record<string, string | string[]>): EntityVisuals => {
    const idleFrames = Array.isArray(idle) ? idle.map(generatePixelArt) : [generatePixelArt(idle)];
    const attackFrames = Array.isArray(attack) ? attack.map(generatePixelArt) : [generatePixelArt(attack)];

    const visuals: EntityVisuals = {
        idle: { frames: idleFrames, fps },
        attack: { frames: attackFrames, fps },
        gridSize: 16
    };

    if (extra) {
        Object.entries(extra).forEach(([key, val]) => {
            const frames = Array.isArray(val) ? val.map(generatePixelArt) : [generatePixelArt(val)];
            visuals[key] = { frames, fps };
        });
    }
    return visuals;
};

// Direction Vectors
export const DIRECTION_VECTORS: Record<AttackDirection, {x: number, y: number}> = {
    'RIGHT': { x: 1, y: 0 },
    'LEFT': { x: -1, y: 0 },
    'UP': { x: 0, y: -1 },
    'DOWN': { x: 0, y: 1 },
    'UP_RIGHT': { x: 0.7, y: -0.7 },
    'DOWN_RIGHT': { x: 0.7, y: 0.7 },
    'UP_LEFT': { x: -0.7, y: -0.7 },
    'DOWN_LEFT': { x: -0.7, y: 0.7 }
};

export const INITIAL_PLANT_STATS: Record<string, PlantConfig> = {
  [BasePlantType.SUNFLOWER]: { 
      type: BasePlantType.SUNFLOWER, name: 'Sunflower', cost: 50, cooldown: 5000, health: 300, icon: '🌻', description: 'Produces sun',
      visuals: createVisuals(ART_SUNFLOWER, undefined, 2),
      abilities: [
          { type: 'PRODUCE_SUN', interval: 8000, sunValue: 25 }
      ]
  },
  [BasePlantType.PEASHOOTER]: { 
      type: BasePlantType.PEASHOOTER, name: 'Peashooter', cost: 100, cooldown: 5000, health: 300, icon: '🌱', description: 'Shoots peas',
      visuals: createVisuals(ART_PEASHOOTER, undefined, 3),
      abilities: [
          { type: 'SHOOT', interval: 1400, damage: 20, projectileType: ProjectileType.NORMAL, range: 10 }
      ]
  },
  [BasePlantType.WALLNUT]: { 
      type: BasePlantType.WALLNUT, name: 'Wall-nut', cost: 50, cooldown: 20000, health: 4000, icon: '🥔', description: 'Blocks zombies',
      visuals: createVisuals(ART_WALLNUT, undefined, 1),
      abilities: [ { type: 'WALL' } ]
  },
  [BasePlantType.SQUASH]: { 
      type: BasePlantType.SQUASH, name: 'Squash', cost: 50, cooldown: 30000, health: 10000, icon: '😠', description: 'Stomps zombies',
      visuals: createVisuals(ART_SQUASH[0], ART_SQUASH[1]),
      abilities: [ { type: 'SQUASH', triggerRange: 0.2, damage: 9999 } ]
  },
  [BasePlantType.CHERRY_BOMB]: {
      type: BasePlantType.CHERRY_BOMB, name: 'Cherry Bomb', cost: 150, cooldown: 20000, health: 300, icon: '🍒', description: 'Explodes nearby zombies',
      visuals: createVisuals(ART_CHERRY_BOMB, undefined, 4),
      abilities: [ { type: 'EXPLODE', cooldown: 1000, damage: 9999, triggerRange: 1.5 } ]
  },
  [BasePlantType.POTATO_MINE]: {
      type: BasePlantType.POTATO_MINE, name: 'Potato Mine', cost: 25, cooldown: 30000, health: 300, icon: '🥔', description: 'Explodes on contact',
      visuals: createVisuals(ART_POTATO_MINE, undefined, 2),
      abilities: [ { type: 'EXPLODE', cooldown: 15000, damage: 9999, triggerRange: 0.2 } ]
  },
  [BasePlantType.SNOW_PEA]: {
      type: BasePlantType.SNOW_PEA, name: 'Snow Pea', cost: 175, cooldown: 5000, health: 300, icon: '❄️', description: 'Shoots frozen peas',
      visuals: createVisuals(ART_SNOW_PEA, undefined, 3),
      abilities: [
          { type: 'SHOOT', interval: 1400, damage: 20, projectileType: ProjectileType.FROZEN }
      ]
  },
  [BasePlantType.CHOMPER]: {
      type: BasePlantType.CHOMPER, name: 'Chomper', cost: 150, cooldown: 5000, health: 300, icon: '🦷', description: 'Eats zombies whole',
      visuals: createVisuals(ART_CHOMPER, undefined, 3),
      abilities: [ { type: 'SQUASH', damage: 9999, triggerRange: 0.2, cooldown: 30000 } ] // Simplified chomper as squash-like for now
  },
  [BasePlantType.REPEATER]: {
      type: BasePlantType.REPEATER, name: 'Repeater', cost: 200, cooldown: 5000, health: 300, icon: '🌱', description: 'Shoots 2 peas',
      visuals: createVisuals(ART_REPEATER, undefined, 3),
      abilities: [
          { type: 'SHOOT', interval: 1400, damage: 20, projectileType: ProjectileType.NORMAL, shotsPerTrigger: 2, multiShotDelay: 150 }
      ]
  },
  [BasePlantType.PUFF_SHROOM]: {
      type: BasePlantType.PUFF_SHROOM, name: 'Puff Shroom', cost: 0, cooldown: 5000, health: 100, icon: '🍄', description: 'Short range shooter',
      visuals: createVisuals(ART_PUFF_SHROOM, undefined, 2),
      abilities: [
          { type: 'SHOOT', interval: 1400, damage: 20, projectileType: ProjectileType.NORMAL, range: 4 }
      ]
  },
  [BasePlantType.SUN_SHROOM]: {
      type: BasePlantType.SUN_SHROOM, name: 'Sun Shroom', cost: 25, cooldown: 5000, health: 100, icon: '🍄', description: 'Gives small sun then big',
      visuals: createVisuals(ART_SUN_SHROOM, undefined, 2),
      abilities: [ { type: 'PRODUCE_SUN', interval: 8000, sunValue: 15 } ]
  },
  [BasePlantType.FUME_SHROOM]: {
      type: BasePlantType.FUME_SHROOM, name: 'Fume Shroom', cost: 75, cooldown: 5000, health: 300, icon: '💨', description: 'Shoots through screen door',
      visuals: createVisuals(ART_FUME_SHROOM, undefined, 3),
      abilities: [ { type: 'SHOOT', interval: 1400, damage: 20 } ]
  },
  [BasePlantType.GRAVE_BUSTER]: {
      type: BasePlantType.GRAVE_BUSTER, name: 'Grave Buster', cost: 75, cooldown: 5000, health: 300, icon: '🪦', description: 'Eats graves',
      visuals: createVisuals(ART_GRAVE_BUSTER, undefined, 2)
  },
  [BasePlantType.HYPNO_SHROOM]: {
      type: BasePlantType.HYPNO_SHROOM, name: 'Hypno Shroom', cost: 75, cooldown: 5000, health: 100, icon: '🌀', description: 'Hypnotizes zombies',
      visuals: createVisuals(ART_HYPNO_SHROOM, undefined, 4)
  },
  [BasePlantType.SCAREDY_SHROOM]: {
      type: BasePlantType.SCAREDY_SHROOM, name: 'Scaredy Shroom', cost: 25, cooldown: 5000, health: 100, icon: '😨', description: 'Long range, hides when close',
      visuals: createVisuals(ART_SCAREDY_SHROOM, undefined, 2),
      abilities: [ { type: 'SHOOT', interval: 1400, damage: 20, range: 10 } ]
  },
  [BasePlantType.ICE_SHROOM]: {
      type: BasePlantType.ICE_SHROOM, name: 'Ice Shroom', cost: 75, cooldown: 50000, health: 100, icon: '🧊', description: 'Freezes all zombies',
      visuals: createVisuals(ART_ICE_SHROOM, undefined, 2),
      abilities: [ { type: 'FREEZE_ALL', damage: 20 } ]
  },
  [BasePlantType.DOOM_SHROOM]: {
      type: BasePlantType.DOOM_SHROOM, name: 'Doom Shroom', cost: 125, cooldown: 50000, health: 100, icon: '💣', description: 'Massive explosion',
      visuals: createVisuals(ART_DOOM_SHROOM, undefined, 2),
      abilities: [ { type: 'EXPLODE', damage: 5000, triggerRange: 2.5, cooldown: 1000 } ]
  },
  [BasePlantType.JALAPENO]: {
      type: BasePlantType.JALAPENO, name: 'Jalapeno', cost: 125, cooldown: 50000, health: 100, icon: '🌶️', description: 'Destroys entire row',
      visuals: createVisuals(ART_JALAPENO, undefined, 4),
      abilities: [ { type: 'BURN_ROW', cooldown: 700, damage: 9999 } ]
  },
  [BasePlantType.SPIKEWEED]: {
      type: BasePlantType.SPIKEWEED, name: 'Spikeweed', cost: 100, cooldown: 5000, health: 300, icon: '🌵', description: 'Hurts zombies stepping on it',
      visuals: createVisuals(ART_SPIKEWEED, undefined, 2),
      abilities: [ { type: 'SQUASH', damage: 10, triggerRange: 0 } ] // Continuous squash
  },
  [BasePlantType.TORCHWOOD]: {
      type: BasePlantType.TORCHWOOD, name: 'Torchwood', cost: 175, cooldown: 5000, health: 300, icon: '🔥', description: 'Ignites peas',
      visuals: createVisuals(ART_TORCHWOOD, undefined, 4),
      abilities: [ { type: 'WALL' } ]
  },
  [BasePlantType.TALLNUT]: {
      type: BasePlantType.TALLNUT, name: 'Tall-nut', cost: 125, cooldown: 20000, health: 8000, icon: '🧱', description: 'Blocks vaulting zombies',
      visuals: createVisuals(ART_TALLNUT, undefined, 1),
      abilities: [ { type: 'BLOCK_VAULT' } ]
  },
  [BasePlantType.MELON_PULT]: {
      type: BasePlantType.MELON_PULT, name: 'Melon-pult', cost: 300, cooldown: 5000, health: 300, icon: '🍉', description: 'Heavy damage',
      visuals: createVisuals(ART_MELON_PULT, undefined, 3),
      abilities: [ { type: 'SHOOT', interval: 2800, damage: 80, projectileType: ProjectileType.MELON } ]
  },
  [BasePlantType.KERNEL_PULT]: {
      type: BasePlantType.KERNEL_PULT, name: 'Kernel-pult', cost: 100, cooldown: 5000, health: 300, icon: '🌽', description: 'Shoots corn and butter',
      visuals: createVisuals(ART_KERNEL_PULT, undefined, 3),
      abilities: [ { type: 'SHOOT', interval: 2800, damage: 20, projectileType: ProjectileType.KERNEL } ]
  },
  [BasePlantType.TWIN_SUNFLOWER]: {
      type: BasePlantType.TWIN_SUNFLOWER, name: 'Twin Sunflower', cost: 150, cooldown: 5000, health: 300, icon: '🌻', description: 'Double sun production',
      visuals: createVisuals(ART_TWIN_SUNFLOWER, undefined, 3),
      abilities: [ { type: 'PRODUCE_SUN', interval: 8000, sunValue: 50 } ]
  },
  [BasePlantType.THREEPEATER]: {
      type: BasePlantType.THREEPEATER, name: 'Threepeater', cost: 325, cooldown: 5000, health: 300, icon: '🌱', description: 'Shoots 3 lanes',
      visuals: createVisuals(ART_THREEPEATER, undefined, 3),
      abilities: [ { type: 'SHOOT', interval: 1400, damage: 20 } ]
  },
  [BasePlantType.GATLING_PEA]: {
      type: BasePlantType.GATLING_PEA, name: 'Gatling Pea', cost: 250, cooldown: 5000, health: 300, icon: '🔫', description: 'Shoots 4 peas',
      visuals: createVisuals(ART_GATLING_PEA, undefined, 4),
      abilities: [ { type: 'SHOOT', interval: 1400, damage: 20, shotsPerTrigger: 4, multiShotDelay: 100 } ]
  },
  [BasePlantType.COB_CANNON]: {
      type: BasePlantType.COB_CANNON, name: 'Cob Cannon', cost: 500, cooldown: 30000, health: 500, icon: '🌽', description: 'Massive manual strike',
      visuals: createVisuals(ART_COB_CANNON, undefined, 2),
      visualScale: 1.5
  },
  [BasePlantType.STARFRUIT]: {
      type: BasePlantType.STARFRUIT, name: 'Starfruit', cost: 125, cooldown: 5000, health: 300, icon: '⭐', description: 'Shoots 5 directions',
      visuals: createVisuals(ART_STARFRUIT, undefined, 3),
      abilities: [ { type: 'SHOOT', interval: 1400, damage: 20 } ]
  }
};

export const EFFECT_DURATIONS = {
  EXPLOSION: 800,
  DOOM_EXPLOSION: 1200,
  FIRE_ROW: 1500,
  FREEZE: 1000, 
  BUTTER_SPLAT: 500,
  ICE_TRAIL: 10000 // Ice trail lasts 10s visually
};

// Increased Speeds
export const INITIAL_ZOMBIE_STATS: Record<string, ZombieStatConfig> = {
  [BaseZombieType.NORMAL]: { 
      health: 200, speed: 0.05, damage: 1, icon: '🧟',
      visuals: createZombieVisuals(ART_ZOMBIE_WALK, ART_ZOMBIE_WALK, 3),
      visualScale: 1.0
  }, 
  [BaseZombieType.CONEHEAD]: { 
      health: 560, speed: 0.05, damage: 1, icon: '🧟‍♂️',
      visuals: createZombieVisuals(ART_ZOMBIE_CONE, ART_ZOMBIE_CONE, 3), 
      visualScale: 1.0
  },
  [BaseZombieType.BUCKETHEAD]: { 
      health: 1300, speed: 0.05, damage: 1, icon: '👺',
      visuals: createZombieVisuals(ART_ZOMBIE_BUCKET, ART_ZOMBIE_BUCKET, 3),
      visualScale: 1.0
  },
  [BaseZombieType.FOOTBALL]: { 
      health: 1400, speed: 0.12, damage: 1, icon: '🏈',
      visuals: createZombieVisuals(ART_ZOMBIE_FOOTBALL, ART_ZOMBIE_FOOTBALL, 4),
      visualScale: 1.0
  },
  [BaseZombieType.NEWSPAPER]: { 
      health: 400, speed: 0.03, damage: 1, icon: '📰',
      visuals: createZombieVisuals(ART_ZOMBIE_NEWSPAPER, ART_ZOMBIE_NEWSPAPER, 3),
      visualScale: 1.0
  },
  [BaseZombieType.SCREEN_DOOR]: { 
      health: 1000, speed: 0.05, damage: 1, icon: '🚪',
      visuals: createZombieVisuals(ART_ZOMBIE_SCREEN, ART_ZOMBIE_SCREEN, 3),
      visualScale: 1.0
  },
  [BaseZombieType.IMP]: {
      health: 100, speed: 0.08, damage: 1, icon: '👶',
      visuals: createZombieVisuals(ART_ZOMBIE_IMP, ART_ZOMBIE_IMP, 4),
      visualScale: 0.7
  },
  [BaseZombieType.GARGANTUAR]: {
      health: 3000, speed: 0.03, damage: 50, icon: '👹',
      visuals: createZombieVisuals(ART_ZOMBIE_GARGANTUAR, ART_ZOMBIE_GARGANTUAR, 2),
      visualScale: 1.5
  },
  [BaseZombieType.MECH_BOSS]: {
      health: 6000, speed: 0.015, damage: 100, icon: '🤖',
      visuals: createZombieVisuals(ART_ZOMBIE_GARGANTUAR, ART_ZOMBIE_GARGANTUAR, 2), // Re-use gargantuar for now but could be unique
      visualScale: 1.6
  },
  // --- SPECIAL ZOMBIES WITH ABILITIES ---
  [BaseZombieType.POLE_VAULTING]: {
      health: 500, speed: 0.12, damage: 1, icon: '🏃',
      visuals: createZombieVisuals(ART_POLE_VAULTING_RUN, ART_ZOMBIE_WALK, 5, { 
          'run': ART_POLE_VAULTING_RUN, 
          'walk': ART_ZOMBIE_WALK,
          'jump': [ART_POLE_VAULTING_JUMP]
      }),
      visualScale: 1.0,
      abilities: [
          { type: 'VAULT', cooldown: 999999, initialCooldown: 0, vaultDistance: 1, duration: 600 }
      ]
  },
  [BaseZombieType.DANCING]: {
      health: 500, speed: 0.04, damage: 1, icon: '🕺',
      visuals: createZombieVisuals(ART_DANCING, ART_DANCING, 4, {
        'summon': [ART_DANCING_SUMMON]
      }),
      visualScale: 1.1,
      abilities: [
          { type: 'SUMMON', cooldown: 8000, initialCooldown: 1000, summonType: BaseZombieType.BACKUP_DANCER, summonCount: 4 }
      ]
  },
  [BaseZombieType.BACKUP_DANCER]: {
      health: 300, speed: 0.04, damage: 1, icon: '👯',
      visuals: createZombieVisuals(ART_BACKUP_DANCER, ART_BACKUP_DANCER, 4),
      visualScale: 1.0
  },
  [BaseZombieType.ZOMBONI]: {
      health: 1500, speed: 0.03, damage: 9999, icon: '🚜',
      visuals: createZombieVisuals(ART_ZOMBONI, ART_ZOMBONI),
      visualScale: 1.5,
      abilities: [
          { type: 'ICE_TRAIL', cooldown: 2000, trailDuration: 10000 },
          { type: 'CRUSH_PLANTS', cooldown: 0 }
      ]
  }
};

export const PROJECTILE_SPEED = 0.7; 
export const CLEANER_SPEED = 0.8; 
export const PROJECTILE_DAMAGE = 20;
export const MELON_DAMAGE = 80;
export const KERNEL_DAMAGE = 20;
export const BUTTER_DAMAGE = 40;
export const COB_DAMAGE = 1800; // Massive damage

// Intervals
export const SUN_GENERATION_INTERVAL = 8000;
export const NATURAL_SUN_INTERVAL = 8000; 
export const WAVE_INTERVAL = 25000; 

// Initial Levels Configuration...
const INITIAL_LEVELS: LevelConfig[] = [
    { 
        id: 1, name: "Level 1-1", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 5, startingSun: 150, enabledZombies: [BaseZombieType.NORMAL], spawnIntervalMultiplier: 1.2, difficulty: 1, seedSlots: 4, unlocksPlant: BasePlantType.SUNFLOWER
    },
    { 
        id: 2, name: "Level 1-2", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 6, startingSun: 200, enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD], spawnIntervalMultiplier: 1.1, difficulty: 2, seedSlots: 5, unlocksPlant: BasePlantType.PEASHOOTER
    },
    {
        id: 10, name: "Level 5-10 (BOSS)", mode: 'CLASSIC', scene: LevelScene.FACTORY, totalWaves: 15, startingSun: 1500, enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.IMP, BaseZombieType.GARGANTUAR, BaseZombieType.MECH_BOSS, BaseZombieType.ZOMBONI], spawnIntervalMultiplier: 1.0, difficulty: 10, seedSlots: 10, unlocksPlant: BasePlantType.COB_CANNON
    }
];

// Mutable Exports
export const PLANT_STATS: Record<string, PlantConfig> = { ...INITIAL_PLANT_STATS };
export const ZOMBIE_STATS: Record<string, ZombieStatConfig> = { ...INITIAL_ZOMBIE_STATS };
export const LEVELS: LevelConfig[] = [ ...INITIAL_LEVELS ];

// Reset Function for DLC Toggling
export const RESTORE_CONSTANTS = () => {
    Object.keys(PLANT_STATS).forEach(key => delete PLANT_STATS[key]);
    Object.keys(ZOMBIE_STATS).forEach(key => delete ZOMBIE_STATS[key]);
    
    Object.assign(PLANT_STATS, INITIAL_PLANT_STATS);
    Object.assign(ZOMBIE_STATS, INITIAL_ZOMBIE_STATS);
    
    LEVELS.length = 0;
    LEVELS.push(...INITIAL_LEVELS);
};

export const CONSUMABLES: Record<ConsumableType, { name: string, icon: string, cost: number, description: string }> = {
    [ConsumableType.SUN_PACK]: { name: 'Sun Crate', icon: '☀️', cost: 1000, description: 'Instantly gives 500 Sun.' },
    [ConsumableType.REPAIR_KIT]: { name: 'Repair Kit', icon: '🔧', cost: 500, description: 'Fully heals all plants.' },
    [ConsumableType.TACTICAL_NUKE]: { name: 'Doom Nuke', icon: '☢️', cost: 2500, description: 'Kills all zombies on screen.' },
    [ConsumableType.TIME_FREEZE]: { name: 'Stopwatch', icon: '⏱️', cost: 1500, description: 'Freezes zombies for 10 seconds.' }
};