
import { PlantConfig, BasePlantType, BaseZombieType, LevelConfig, PlantType, ZombieType, LevelScene, ZombieStatConfig, EntityVisuals, AttackDirection, ConsumableType, ProjectileType, TrajectoryType } from './types';

export const ROWS = 6;
export const COLS = 9;
export const TICK_RATE = 16; 

export const CELL_WIDTH = 80; 
export const CELL_HEIGHT = 90;
export const MAX_DECK_SIZE = 8;
export const TOTAL_WAVES = 10;

// --- PIXEL ART ENGINE ---

const PALETTE: Record<string, string> = {
  '.': 'rgba(0,0,0,0)', // Transparent
  'K': '#000000', // Black
  'W': '#FFFFFF', // White
  'G': '#6B7280', // Grey
  'R': '#DC2626', // Red
  'r': '#EF4444', // Light Red
  'O': '#EA580C', // Dark Orange
  'o': '#F97316', // Orange
  'Y': '#CA8A04', // Dark Yellow
  'y': '#FACC15', // Yellow
  'L': '#65A30D', // Dark Lime
  'l': '#84CC16', // Lime
  'g': '#16A34A', // Green
  'd': '#14532D', // Dark Green
  'C': '#0891B2', // Cyan
  'c': '#22D3EE', // Light Cyan
  'B': '#2563EB', // Blue
  'b': '#60A5FA', // Light Blue
  'P': '#9333EA', // Purple
  'p': '#C084FC', // Light Purple
  'M': '#DB2777', // Magenta
  'm': '#F472B6', // Pink
  'N': '#78350F', // Brown
  'n': '#92400E', // Light Brown
  'S': '#D1D5DB', // Silver
};

const generatePixelArt = (ascii: string): string => {
    const canvas = document.createElement('canvas');
    canvas.width = 16;
    canvas.height = 16;
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';
    ctx.clearRect(0, 0, 16, 16);
    const rows = ascii.trim().split('\n').map(r => r.trim());
    rows.forEach((row, y) => {
        for (let x = 0; x < Math.min(row.length, 16); x++) {
            const char = row[x];
            if (PALETTE[char]) {
                ctx.fillStyle = PALETTE[char];
                ctx.fillRect(x, y, 1, 1);
            }
        }
    });
    return canvas.toDataURL('image/png');
};

// --- PLANT SPRITES ---

const ART_SUNFLOWER = `
.....ooo.....
....oyyyos...
...oyNyyoy...
...oNyyNNo...
...oyNNyy....
....oyyy.....
.....gg......
....glg......
.....g.......
.....g.......
`;

const ART_PEASHOOTER = `
......gg.....
.....gllg....
....gllKlg...
...glllllgg..
..gllllllg...
...gggggg....
.....g.......
....glg......
...g.g.......
`;

const ART_WALLNUT = `
....NNN......
...NnnNN.....
..NnnnnNN....
..NnKKnNN....
..NnnnnNN....
...NnnNN.....
....NNN......
`;

const ART_CHERRY_BOMB = `
......g.g....
.....g...g...
....R.....R..
...RRR...RRR.
..RRRRR.RRRRR
..RRRRR.RRRRR
...RRR...RRR.
....R.....R..
`;

const ART_POTATO_MINE = `
......r......
......R......
.....nNn.....
....nnnnn....
...nnnnnnn...
..nnnnnnnnn..
.nnnnnnnnnnn.
`;

const ART_SNOW_PEA = `
......CC.....
.....CccC....
....CccKc....
...CcccccCC..
..CccccccC...
...CCCCCC....
.....g.......
....glg......
...g.g.......
`;

const ART_CHOMPER = `
.....PPP.....
....PpppP....
...PWWWWW....
..PWWWWWWW...
..PWWWWWWW...
...Pppppp....
....PPPPP....
.....g.......
....glg......
...g.g.......
`;

const ART_REPEATER = `
......gg.....
.....gllg....
....gllKlg...
..gglllllgg..
.gllgllllg...
.glKlg.gg....
..ggg..g.....
......glg....
.....g.g.....
`;

const ART_PUFF_SHROOM = `
.....ppp.....
....ppppp....
...ppppppp...
...ppppppp...
....ppppp....
.....PPP.....
.....PPP.....
.....PPP.....
`;

const ART_SUN_SHROOM = `
.....yyy.....
....yyyyy....
...yyyyyyy...
...yyyyyyy...
....yyyyy....
.....YYY.....
.....YYY.....
.....YYY.....
`;

const ART_FUME_SHROOM = `
....PPPPP....
...PpppppP...
..PpppppppP..
..PpppppppP..
...PpppppP...
....PPPPP....
.....PPP.....
.....PPP.....
.....PPP.....
`;

const ART_GRAVE_BUSTER = `
....ddddd....
...dgggggd...
..dgggggggd..
..dggKggKgd..
..dgggggggd..
..dggKKKggd..
...dgggggd...
....ddddd....
`;

const ART_HYPNO_SHROOM = `
.....mMm.....
....MmMmM....
...mMmMmMm...
...MmMmMmM...
....mMmMm....
.....PPP.....
.....PPP.....
.....PPP.....
`;

const ART_SCAREDY_SHROOM = `
.....ppp.....
....ppppp....
...ppppppp...
....ppppp....
.....PPP.....
.....PPP.....
.....PPP.....
.....PPP.....
.....PPP.....
`;

const ART_ICE_SHROOM = `
.....CCC.....
....ccccc....
...ccccccc...
...ccccccc...
....ccccc....
.....BBB.....
.....BBB.....
.....BBB.....
`;

const ART_DOOM_SHROOM = `
.....GGG.....
....GGGGG....
...GGGGGGG...
...GGKGGKG...
....GGGGG....
.....KKK.....
.....KKK.....
.....KKK.....
`;

const ART_SQUASH = `
.....ggg.....
....ggggg....
...ggggggg...
...ggKggKg...
...ggggggg...
...ggggggg...
....ggggg....
.....ggg.....
`;

const ART_JALAPENO = `
......g......
.....RRR.....
....RRRRR....
...RRRRRRR...
...RRKRRKR...
...RRRRRRR...
...RRRRRRR...
....RRRRR....
.....RRR.....
`;

const ART_SPIKEWEED = `
.............
.............
.............
..S...S...S..
.SgS.SgS.SgS.
.ggg.ggg.ggg.
ggggggggggggg
`;

const ART_TORCHWOOD = `
.....ror.....
....rOyOr....
...rOyyyOr...
...NNNNNNN...
...NnnnnNN...
...NnKKnnN...
...NnnnnNN...
...NNNNNNN...
`;

const ART_TALLNUT = `
....NNN......
...NnnNN.....
..NnnnnNN....
..NnKKnNN....
..NnnnnNN....
..NnnnnNN....
..NnnnnNN....
...NnnNN.....
....NNN......
`;

const ART_MELON_PULT = `
.....ggg.....
....ggggg....
...ggllgg....
..ggllllgg...
..ggllllgg...
...gggggg....
...g....g....
..ggg..ggg...
`;

const ART_KERNEL_PULT = `
.....yyy.....
....yyyyy....
...yyNNyy....
..yyNNNNyy...
..yyNNNNyy...
...yyyyyy....
...y....y....
..yyy..yyy...
`;

const ART_COB_CANNON = `
..............
.yyy......yyy.
yyyyy....yyyyy
yyyyy....yyyyy
.yyy.GGGG.yyy.
.....GGGG.....
.....GGGG.....
..WWWWWWWWWW..
.WWWWWWWWWWWW.
..WWWWWWWWWW..
`;

const ART_STARFRUIT = `
......y......
.....yyy.....
....yyyyy....
yy..yyKyy..yy
.yyyyyyy...y.
..yyyyyyy.yy.
...yyyyyyy...
..yy..y..yy..
.y....y....y.
`;

const ART_THREEPEATER = `
...g..g..g...
..glg.g.glg..
..glg.g.glg..
...g..g..g...
....ggggg....
.....ggg.....
......g......
.....glg.....
....g.g.g....
`;

const ART_GATLING_PEA = `
.....GGgg....
....GGllg....
...GGllKlg...
..GGlllllgg..
.gGllgllllg..
.glKlg.gg....
..ggg..g.....
......glg....
.....g.g.....
`;

const ART_TWIN_SUNFLOWER = `
...oo....oo..
..oyyo..oyyo.
..yNNy..yNNy.
..oyyo..oyyo.
...oo....oo..
.....gggg....
......gg.....
.....glg.....
......g......
`;

// Helper to assign pixel art
const withArt = (stats: PlantConfig, ascii: string): PlantConfig => {
    return {
        ...stats,
        visuals: {
            idle: {
                frames: [generatePixelArt(ascii)],
                fps: 0
            }
        }
    };
};

const ART_LAWN_MOWER = `
...........ss...
..........s.....
.........s......
........s.......
.......s.RRRR...
......RRRRRRRR..
.....RRRGGGRRR..
.....RRRGGGRRR..
.....RRRRRRRRR..
.....RRRRRRRRR..
.....KK....KK...
.....KK....KK...
`;
export const LAWN_MOWER_ICON = generatePixelArt(ART_LAWN_MOWER);

export const DIRECTION_VECTORS: Record<AttackDirection, {x: number, y: number}> = {
    'RIGHT': { x: 1, y: 0 },
    'LEFT': { x: -1, y: 0 },
    'UP': { x: 0, y: -1 },
    'DOWN': { x: 0, y: 1 },
    'UP_RIGHT': { x: 0.7, y: -0.7 },
    'DOWN_RIGHT': { x: 0.7, y: 0.7 },
    'UP_LEFT': { x: -0.7, y: -0.7 },
    'DOWN_LEFT': { x: -0.7, y: 0.7 }
};

export const PROJECTILE_SPEED = 0.7; 
export const CLEANER_SPEED = 0.8; 
export const PROJECTILE_DAMAGE = 20;
export const MELON_DAMAGE = 80;
export const KERNEL_DAMAGE = 20;
export const BUTTER_DAMAGE = 40;
export const COB_DAMAGE = 1800;

export const SUN_GENERATION_INTERVAL = 4000;
export const NATURAL_SUN_INTERVAL = 4000;
export const WAVE_INTERVAL = 20000;

export const EFFECT_DURATIONS = {
    EXPLOSION: 1000,
    FIRE_ROW: 2000,
    FREEZE: 5000,
    BUTTER: 3000,
    DOOM_EXPLOSION: 2000,
    ICE_TRAIL: 5000
};

export const INITIAL_PLANT_STATS: Record<string, PlantConfig> = {
    [BasePlantType.SUNFLOWER]: withArt({ type: BasePlantType.SUNFLOWER, name: 'Sunflower', cost: 50, cooldown: 5000, health: 300, icon: '🌻', description: 'Produces sun.', abilities: [{ type: 'PRODUCE_SUN', interval: 4000, sunValue: 25 }] }, ART_SUNFLOWER),
    [BasePlantType.PEASHOOTER]: withArt({ type: BasePlantType.PEASHOOTER, name: 'Peashooter', cost: 100, cooldown: 5000, health: 300, icon: '🌱', description: 'Shoots peas.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, range: 10, projectileType: ProjectileType.NORMAL }] }, ART_PEASHOOTER),
    [BasePlantType.WALLNUT]: withArt({ type: BasePlantType.WALLNUT, name: 'Wall-nut', cost: 50, cooldown: 20000, health: 4000, icon: '🌰', description: 'Blocks zombies.', abilities: [] }, ART_WALLNUT),
    [BasePlantType.CHERRY_BOMB]: withArt({ type: BasePlantType.CHERRY_BOMB, name: 'Cherry Bomb', cost: 150, cooldown: 30000, health: 300, icon: '🍒', description: 'Explodes area.', abilities: [{ type: 'EXPLODE', damage: 1800, triggerRange: 1.5, cooldown: 1000 }] }, ART_CHERRY_BOMB),
    [BasePlantType.POTATO_MINE]: withArt({ type: BasePlantType.POTATO_MINE, name: 'Potato Mine', cost: 25, cooldown: 20000, health: 300, icon: '🥔', description: 'Explodes on contact.', abilities: [] }, ART_POTATO_MINE),
    [BasePlantType.SNOW_PEA]: withArt({ type: BasePlantType.SNOW_PEA, name: 'Snow Pea', cost: 175, cooldown: 5000, health: 300, icon: '❄️', description: 'Shoots frozen peas.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, range: 10, projectileType: ProjectileType.FROZEN }] }, ART_SNOW_PEA),
    [BasePlantType.CHOMPER]: withArt({ type: BasePlantType.CHOMPER, name: 'Chomper', cost: 150, cooldown: 5000, health: 300, icon: '🐊', description: 'Eats zombies whole.', abilities: [] }, ART_CHOMPER),
    [BasePlantType.REPEATER]: withArt({ type: BasePlantType.REPEATER, name: 'Repeater', cost: 200, cooldown: 5000, health: 300, icon: '🌿', description: 'Shoots two peas.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, range: 10, shotsPerTrigger: 2, multiShotDelay: 150 }] }, ART_REPEATER),
    [BasePlantType.PUFF_SHROOM]: withArt({ type: BasePlantType.PUFF_SHROOM, name: 'Puff-shroom', cost: 0, cooldown: 5000, health: 200, icon: '🍄', description: 'Short range shooter.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, range: 3 }] }, ART_PUFF_SHROOM),
    [BasePlantType.SUN_SHROOM]: withArt({ type: BasePlantType.SUN_SHROOM, name: 'Sun-shroom', cost: 25, cooldown: 5000, health: 200, icon: '🔆', description: 'Produces small sun initially.', abilities: [{ type: 'PRODUCE_SUN', interval: 10000, sunValue: 15 }] }, ART_SUN_SHROOM),
    [BasePlantType.FUME_SHROOM]: withArt({ type: BasePlantType.FUME_SHROOM, name: 'Fume-shroom', cost: 75, cooldown: 5000, health: 300, icon: '💨', description: 'Shoots fumes passing through shields.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, range: 4 }] }, ART_FUME_SHROOM),
    [BasePlantType.GRAVE_BUSTER]: withArt({ type: BasePlantType.GRAVE_BUSTER, name: 'Grave Buster', cost: 75, cooldown: 5000, health: 300, icon: '🪦', description: 'Eats graves.', abilities: [] }, ART_GRAVE_BUSTER),
    [BasePlantType.HYPNO_SHROOM]: withArt({ type: BasePlantType.HYPNO_SHROOM, name: 'Hypno-shroom', cost: 75, cooldown: 5000, health: 200, icon: '😵', description: 'Hypnotizes zombies.', abilities: [] }, ART_HYPNO_SHROOM),
    [BasePlantType.SCAREDY_SHROOM]: withArt({ type: BasePlantType.SCAREDY_SHROOM, name: 'Scaredy-shroom', cost: 25, cooldown: 5000, health: 200, icon: '😨', description: 'Long range shooter, hides when close.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, range: 10 }] }, ART_SCAREDY_SHROOM),
    [BasePlantType.ICE_SHROOM]: withArt({ type: BasePlantType.ICE_SHROOM, name: 'Ice-shroom', cost: 75, cooldown: 30000, health: 200, icon: '🧊', description: 'Freezes all zombies.', abilities: [{ type: 'FREEZE_ALL', damage: 20 }] }, ART_ICE_SHROOM),
    [BasePlantType.DOOM_SHROOM]: withArt({ type: BasePlantType.DOOM_SHROOM, name: 'Doom-shroom', cost: 125, cooldown: 30000, health: 200, icon: '☢️', description: 'Massive explosion.', abilities: [{ type: 'EXPLODE', damage: 1800, triggerRange: 3.5, cooldown: 1000 }] }, ART_DOOM_SHROOM),
    [BasePlantType.SQUASH]: withArt({ type: BasePlantType.SQUASH, name: 'Squash', cost: 50, cooldown: 20000, health: 300, icon: '😠', description: 'Smashes zombies.', abilities: [{ type: 'SQUASH', damage: 1800, triggerRange: 0.5 }] }, ART_SQUASH),
    [BasePlantType.JALAPENO]: withArt({ type: BasePlantType.JALAPENO, name: 'Jalapeno', cost: 125, cooldown: 30000, health: 300, icon: '🌶️', description: 'Burns a whole row.', abilities: [{ type: 'BURN_ROW', damage: 1800, cooldown: 1000 }] }, ART_JALAPENO),
    [BasePlantType.SPIKEWEED]: withArt({ type: BasePlantType.SPIKEWEED, name: 'Spikeweed', cost: 100, cooldown: 5000, health: 300, icon: '🌵', description: 'Hurts zombies walking over it.', abilities: [] }, ART_SPIKEWEED),
    [BasePlantType.MELON_PULT]: withArt({ type: BasePlantType.MELON_PULT, name: 'Melon-pult', cost: 300, cooldown: 5000, health: 300, icon: '🍉', description: 'Heavy damage lobbed shot.', abilities: [{ type: 'SHOOT', interval: 2800, damage: 80, range: 10, projectileType: ProjectileType.MELON, trajectory: TrajectoryType.PARABOLIC }] }, ART_MELON_PULT),
    [BasePlantType.KERNEL_PULT]: withArt({ type: BasePlantType.KERNEL_PULT, name: 'Kernel-pult', cost: 100, cooldown: 5000, health: 300, icon: '🌽', description: 'Lobs corn and butter.', abilities: [{ type: 'SHOOT', interval: 2800, damage: 20, range: 10, projectileType: ProjectileType.KERNEL, trajectory: TrajectoryType.PARABOLIC }] }, ART_KERNEL_PULT),
    [BasePlantType.TWIN_SUNFLOWER]: withArt({ type: BasePlantType.TWIN_SUNFLOWER, name: 'Twin Sunflower', cost: 150, cooldown: 5000, health: 300, icon: '🌻🌻', description: 'Double sun.', abilities: [{ type: 'PRODUCE_SUN', interval: 10000, sunValue: 50 }] }, ART_TWIN_SUNFLOWER),
    [BasePlantType.THREEPEATER]: withArt({ type: BasePlantType.THREEPEATER, name: 'Threepeater', cost: 325, cooldown: 5000, health: 300, icon: '🌿3', description: 'Shoots 3 lanes.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20 }] }, ART_THREEPEATER),
    [BasePlantType.GATLING_PEA]: withArt({ type: BasePlantType.GATLING_PEA, name: 'Gatling Pea', cost: 250, cooldown: 5000, health: 300, icon: '🔫', description: 'Rapid fire.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, shotsPerTrigger: 4, multiShotDelay: 100 }] }, ART_GATLING_PEA),
    [BasePlantType.TORCHWOOD]: withArt({ type: BasePlantType.TORCHWOOD, name: 'Torchwood', cost: 175, cooldown: 5000, health: 300, icon: '🔥', description: 'Ignites peas.', abilities: [] }, ART_TORCHWOOD),
    [BasePlantType.TALLNUT]: withArt({ type: BasePlantType.TALLNUT, name: 'Tall-nut', cost: 125, cooldown: 20000, health: 8000, icon: '🥜', description: 'Blocks vaulting.', abilities: [{ type: 'BLOCK_VAULT' }] }, ART_TALLNUT),
    [BasePlantType.COB_CANNON]: withArt({ type: BasePlantType.COB_CANNON, name: 'Cob Cannon', cost: 500, cooldown: 5000, health: 1000, icon: '🌽💣', description: 'Manual launch deadly cob.', visualScale: 2.0, abilities: [{ type: 'SHOOT', interval: 0, cooldown: 35000, flightDuration: 2000, arcHeight: 300, damage: 1800, projectileType: ProjectileType.COB, trajectory: TrajectoryType.LOBBED }] }, ART_COB_CANNON),
    [BasePlantType.STARFRUIT]: withArt({ type: BasePlantType.STARFRUIT, name: 'Starfruit', cost: 125, cooldown: 5000, health: 300, icon: '⭐', description: 'Shoots stars in 5 directions.', abilities: [{ type: 'SHOOT', interval: 1400, damage: 20, projectileType: ProjectileType.STAR }] }, ART_STARFRUIT),
    [BasePlantType.PLACEHOLDER]: { type: BasePlantType.PLACEHOLDER, name: 'Placeholder', cost: 0, cooldown: 0, health: 1, icon: '', description: 'Occupied space' },
};

export const PLANT_STATS: Record<string, PlantConfig> = JSON.parse(JSON.stringify(INITIAL_PLANT_STATS));

export const INITIAL_ZOMBIE_STATS: Record<string, ZombieStatConfig> = {
    [BaseZombieType.NORMAL]: { health: 200, speed: 0.02, damage: 1, icon: '🧟', visuals: { idle: { frames: [], fps: 5 } } },
    [BaseZombieType.CONEHEAD]: { health: 560, speed: 0.02, damage: 1, icon: '🧟⚠️' },
    [BaseZombieType.BUCKETHEAD]: { health: 1300, speed: 0.02, damage: 1, icon: '🧟🪣' },
    [BaseZombieType.FOOTBALL]: { health: 1600, speed: 0.05, damage: 1, icon: '🧟🏈' },
    [BaseZombieType.NEWSPAPER]: { health: 420, speed: 0.02, damage: 1, icon: '🧟📰' },
    [BaseZombieType.SCREEN_DOOR]: { health: 1300, speed: 0.02, damage: 1, icon: '🧟🚪' },
    [BaseZombieType.POLE_VAULTING]: { health: 500, speed: 0.04, damage: 1, icon: '🧟💈', abilities: [{ type: 'VAULT', duration: 800, vaultDistance: 1.5 }] },
    [BaseZombieType.DANCING]: { health: 500, speed: 0.03, damage: 1, icon: '🧟🕺', abilities: [{ type: 'SUMMON', summonType: BaseZombieType.BACKUP_DANCER, summonCount: 4, cooldown: 10000 }] },
    [BaseZombieType.BACKUP_DANCER]: { health: 200, speed: 0.03, damage: 1, icon: '🧟👯' },
    [BaseZombieType.ZOMBONI]: { health: 1300, speed: 0.02, damage: 1, icon: '🚗', abilities: [{ type: 'ICE_TRAIL', trailDuration: 10000 }, { type: 'CRUSH_PLANTS' }] },
    [BaseZombieType.IMP]: { health: 100, speed: 0.04, damage: 1, icon: '🧟👶' },
    [BaseZombieType.GARGANTUAR]: { health: 3000, speed: 0.03, damage: 5, icon: '🧟💪', abilities: [{ type: 'CRUSH_PLANTS' }] },
    [BaseZombieType.MECH_BOSS]: { health: 10000, speed: 0.01, damage: 10, icon: '🤖', abilities: [{ type: 'CRUSH_PLANTS' }] },
};

export const ZOMBIE_STATS: Record<string, ZombieStatConfig> = JSON.parse(JSON.stringify(INITIAL_ZOMBIE_STATS));

export const INITIAL_LEVELS: LevelConfig[] = [
    { id: 1, name: "Day 1-1", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 5, startingSun: 150, enabledZombies: [BaseZombieType.NORMAL], difficulty: 1, seedSlots: 6 },
    { id: 2, name: "Day 1-2", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 8, startingSun: 150, enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD], difficulty: 2, seedSlots: 6, unlocksPlant: BasePlantType.SUNFLOWER },
    { id: 3, name: "Day 1-3", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 10, startingSun: 200, enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD, BaseZombieType.BUCKETHEAD], difficulty: 3, seedSlots: 7, unlocksPlant: BasePlantType.CHERRY_BOMB },
    { id: 4, name: "Day 1-4", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 10, startingSun: 250, enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD, BaseZombieType.BUCKETHEAD, BaseZombieType.POLE_VAULTING], difficulty: 4, seedSlots: 8, unlocksPlant: BasePlantType.WALLNUT },
    { id: 5, name: "Day 1-5", mode: 'CLASSIC', scene: LevelScene.LAWN_DAY, totalWaves: 15, startingSun: 300, enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD, BaseZombieType.BUCKETHEAD, BaseZombieType.POLE_VAULTING, BaseZombieType.NEWSPAPER], difficulty: 5, seedSlots: 9, unlocksPlant: BasePlantType.POTATO_MINE }
];

export const LEVELS: LevelConfig[] = JSON.parse(JSON.stringify(INITIAL_LEVELS));

export const CONSUMABLES: Record<string, { name: string, description: string, cost: number, icon: string }> = {
    [ConsumableType.SUN_PACK]: { name: "Sun Pack", description: "Instantly gain 500 sun.", cost: 1000, icon: "☀️" },
    [ConsumableType.REPAIR_KIT]: { name: "Repair Kit", description: "Heal all plants to full health.", cost: 1500, icon: "🔧" },
    [ConsumableType.TACTICAL_NUKE]: { name: "Tactical Nuke", description: "Kill all zombies on screen.", cost: 5000, icon: "☢️" },
    [ConsumableType.TIME_FREEZE]: { name: "Time Freeze", description: "Freeze all zombies for 10 seconds.", cost: 2500, icon: "❄️" }
};

export const RESTORE_CONSTANTS = () => {
    // Restore Plants
    for (const key in PLANT_STATS) delete PLANT_STATS[key];
    Object.assign(PLANT_STATS, JSON.parse(JSON.stringify(INITIAL_PLANT_STATS)));

    // Restore Zombies
    for (const key in ZOMBIE_STATS) delete ZOMBIE_STATS[key];
    Object.assign(ZOMBIE_STATS, JSON.parse(JSON.stringify(INITIAL_ZOMBIE_STATS)));
    
    // Restore Levels
    LEVELS.length = 0;
    LEVELS.push(...JSON.parse(JSON.stringify(INITIAL_LEVELS)));
};
