

import { PlantConfig, BasePlantType, BaseZombieType, LevelConfig, PlantType, ZombieType, LevelScene, ZombieStatConfig, EntityVisuals, AttackDirection, ConsumableType } from './types';

export const ROWS = 5;
export const COLS = 9;
export const TICK_RATE = 16; // ~60 FPS

export const CELL_WIDTH = 80; 
export const CELL_HEIGHT = 90;
export const MAX_DECK_SIZE = 8;
export const TOTAL_WAVES = 10; // Default fallback

// --- PIXEL ART GENERATOR ---

const PALETTE: Record<string, string> = {
  '.': 'rgba(0,0,0,0)', // Transparent
  'K': '#000000', // Black
  'W': '#FFFFFF', // White
  'G': '#6B7280', // Grey (Iron)
  'R': '#EF4444', // Red
  'O': '#F97316', // Orange
  'Y': '#FACC15', // Yellow
  'L': '#84CC16', // Lime
  'g': '#22C55E', // Green (Plant base)
  'd': '#14532D', // Dark Green (Shadows)
  'T': '#06B6D4', // Teal/Cyan (Ice)
  'B': '#3B82F6', // Blue
  'P': '#9333EA', // Purple
  'M': '#D946EF', // Magenta
  'b': '#7C2D12', // Brown
  'D': '#451a03', // Dark Brown
  'z': '#86EFAC', // Zombie Skin
  'c': '#1E3A8A', // Dark Blue (Clothes)
  's': '#9CA3AF', // Stone/Silver
};

const generatePixelArt = (ascii: string): string => {
    const canvas = document.createElement('canvas');
    canvas.width = 16;
    canvas.height = 16;
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';
    
    // Clear
    ctx.clearRect(0, 0, 16, 16);

    const rows = ascii.trim().split('\n').map(r => r.trim());
    
    rows.forEach((row, y) => {
        for (let x = 0; x < Math.min(row.length, 16); x++) {
            const char = row[x];
            if (PALETTE[char]) {
                ctx.fillStyle = PALETTE[char];
                ctx.fillRect(x, y, 1, 1);
            }
        }
    });
    
    return canvas.toDataURL('image/png');
};

// --- ASCII TEMPLATES ---

const ART_SUNFLOWER = `
.....YOY........
...YYOYOYY......
..YOYOOOYOY.....
..YOOOOOOOY.....
...YYOYOYY......
.....YOY........
......g.........
.....gdg........
....gdgdg.......
...g.gdg.g......
..g..gdg..g.....
`;

const ART_PEASHOOTER = `
......ggg.......
.....ggggg......
....ggKgg.......
...ggKgg...gg...
...ggggg..gggg..
....ggg...gggg..
.....g.....gg...
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......
`;

const ART_WALLNUT = `
.....bbb........
...bbbbbbb......
..bbbbbbbbb.....
..bbKbbbKbb.....
..bbbbbbbbb.....
..bbbbbbbbb.....
...bbbbbbb......
....bbbbb.......
................
................
................
`;

const ART_CHERRY_BOMB = `
.......g.g......
......g...g.....
.....g.....g....
....R.......R...
...RRR.....RRR..
..RRRRR...RRRRR.
..RRRRR...RRRRR.
..RRRRR...RRRRR.
...RRR.....RRR..
....R.......R...
`;

const ART_POTATO_MINE = `
................
................
......r.........
.....dbd........
....dbbbd.......
...dbbbbbd......
..dbbbbbbbd.....
.dbbbbbbbbbd....
................
................
`;

const ART_SNOW_PEA = `
......TTT.......
.....TTTTT......
....TTKTT.......
...TTKTT...TT...
...TTTTT..TTTT..
....TTT...TTTT..
.....g.....TT...
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......
`;

const ART_CHOMPER = `
.......PPP......
......PPPPP.....
.....PPKKKPP....
.....PPKKKPP....
...PPPPWKWPPPP..
..P....WKW...P..
.......PPP......
.......gdg......
......gdgdg.....
.....g.gdg.g....
`;

const ART_REPEATER = `
......ggg.......
...g.ggggg......
..gg.ggKgg......
..gg.ggKgg......
...g.ggggg......
....ggg.ggg.....
.....g...g......
.....g..........
....gdg.........
...g.g.g........
..g..g..g.......
`;

const ART_PUFF_SHROOM = `
................
.....PPPPP......
....PPPPPPP.....
....PPdPdPP.....
....PPPPPPP.....
.....WWWWW......
.....WWWWW......
......WWW.......
................
................
`;

const ART_SUN_SHROOM = `
................
......YYY.......
.....YYYYY......
.....YdYdY......
.....YYYYY......
......bbb.......
......bbb.......
......bbb.......
................
................
`;

const ART_FUME_SHROOM = `
.......PP.......
.....PPPPPP.....
....PPPPPPPP....
...PPPdPPPdPP...
...PPPPPPPPP....
.....PPPPP......
......bbb.......
......bbb.......
......bbb.......
................
`;

const ART_SQUASH = `
................
.....ggggg......
....ggggggg.....
...ggggggggg....
...ggKgggKgg....
...ggggggggg....
...ggggggggg....
...ggggggggg....
....ggggggg.....
................
`;

const ART_JALAPENO = `
.......g........
......RR........
.....RRRR.......
....RRRRR.......
....RRKRR.......
....RRKRR.......
....RRRRR.......
....RRRRR.......
.....RRR........
......R.........
`;

const ART_SPIKEWEED = `
................
................
................
.s.s.s.s.s.s.s..
..s.s.s.s.s.s...
.ggggggggggggg..
ggggggggggggggg.
ggggggggggggggg.
................
................
`;

const ART_MELON_PULT = `
................
......ggg.......
.....ggggg......
....ggdgdgg.....
...ggggggggg....
...ggggggggg....
.....g...g......
....g.....g.....
...g.......g....
................
`;

const ART_KERNEL_PULT = `
................
......YYY.......
.....YYYYY......
....YYdYdYY.....
...YYYYYYYYY....
...YYYYYYYYY....
.....g...g......
....g.....g.....
...g.......g....
................
`;

const ART_TORCHWOOD = `
......O.O.......
.....O.Y.O......
....bObYbOb.....
....bbbbbbb.....
....bbKbbKb.....
....bbbbbbb.....
....bbbbbbb.....
....bb.b.bb.....
...b.......b....
................
`;

const ART_THREEPEATER = `
...g...g...g....
..ggg.ggg.ggg...
..gKg.gKg.gKg...
..ggg.ggg.ggg...
...g...g...g....
...g...g...g....
....g..g..g.....
.....g.g.g......
......gdg.......
.....g.g.g......
`;

const ART_TALLNUT = `
.....bbbb.......
....bbbbbb......
...bbbbbbbb.....
...bbKbbKbb.....
...bbbbbbbb.....
...bbbbbbbb.....
...bbbbbbbb.....
...bbbbbbbb.....
....bbbbbb......
................
`;

const ART_STARFRUIT = `
.......Y........
.......Y........
...Y...Y...Y....
...YY..Y..YY....
....YYYYYYY.....
....YYYYYYY.....
....YYKYKYY.....
...YY..Y..YY....
..YY...Y...YY...
.......Y........
`;

// Armed Cob Cannon (With Corn)
const ART_COB_CANNON = `
..............LL
.bbbbbb.......LL
bYYYYYYb.....LLL
bYYYYYYYYb...LLL
bYYYYYYYYb..LLLL
bbbbbbbbbbbbLLLL
GGGGGGGGGGGGGG..
.G..G..G..G..G..
GGGGGGGGGGGGGG..
.O.O......O.O...
`;

// Charging Cob Cannon (Empty Bed)
const ART_COB_CANNON_CHARGING = `
................
.bbbbbb.........
b.bbbb.b........
b..bbbb..b......
b..bbbb..b......
bbbbbbbbbbbb....
GGGGGGGGGGGGGG..
.G..G..G..G..G..
GGGGGGGGGGGGGG..
.O.O......O.O...
`;

// --- ZOMBIE ARTS ---

const ART_ZOMBIE = `
......zzzz......
.....zzzzzz.....
.....zzKzzK.....
......zzzz......
....ccczzccc....
...cccczzcccc...
...c.cczzcc.c...
.....cczzcc.....
.....bb..bb.....
.....bb..bb.....
.....K....K.....
`;

const ART_CONEHEAD = `
.......O........
......OOO.......
.....OOOOO......
.....OOOOO......
......zzzz......
.....zzKzzK.....
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....
`;

const ART_BUCKETHEAD = `
......GGGG......
.....GGGGGG.....
.....GGGGGG.....
.....G.GG.G.....
......zzzz......
.....zzKzzK.....
....ccczzccc....
...cccczzcccc...
.....cczzcc.....
.....bb..bb.....
`;

const ART_FOOTBALL = `
......RRRR......
.....RRRRRR.....
.....RRRRRR.....
......zzzz......
....RRRzzRRR....
...RRRRzzRRRR...
...R.RRzzRR.R...
.....RRzzRR.....
.....RR..RR.....
`;

const ART_NEWSPAPER = `
......zzzz......
.....zzKzzK.....
......zzzz......
....WWWWWW......
...WWWWWWWW.....
...WWWWWWWW.....
...WWWWWWWW.....
.....cczzcc.....
.....bb..bb.....
`;

const ART_SCREEN_DOOR = `
...GGGGGGGG.....
...G......G.....
...G.zzzz.G.....
...GzzKzzKG.....
...G.zzzz.G.....
...GcczzccG.....
...GcczzccG.....
...G.cczz.G.....
...G.bb...G.....
...GGGGGGGG.....
`;

const ART_GARGANTUAR = `
...zzzzzzzz.....
..zzzzzzzzzz....
..zzKzzzzKzz....
..zzzzzzzzzz....
...RRRRRRRR.....
..RRRRRRRRRR....
.zzRRRRRRRRzz...
.zzRRRRRRRRzz...
..RRRRRRRRRR....
...bbbbbbbb.....
...bb....bb.....
`;

const ART_IMP = `
................
................
................
................
......zzzz......
.....zzzzzz.....
....OOzzzzOO....
....OOzzzzOO....
......zzzz......
......bbbb......
`;

const ART_MECH_BOSS = `
...MMMMMMMM.....
..MMMMMMMMMM....
..MMTMMMMTMM....
..MMMMMMMMMM....
...GGGGGGGG.....
..GGGGGGGGGG....
.GGGGGGGGGGGG...
.GGGGGGGGGGGG...
..GGGGGGGGGG....
...ssssssss.....
...ss....ss.....
`;

// --- STATS ---

const PIXEL_ZOMBIE_DEFAULT = generatePixelArt(ART_ZOMBIE);

// Helper to create visual config
const createVisuals = (idleAscii: string, fps = 5): EntityVisuals => ({
    idle: { frames: [generatePixelArt(idleAscii)], fps },
    gridSize: 16
});

// Helper for Zombies
const createZombieVisuals = (idleAscii: string, attackAscii: string, fps = 5): EntityVisuals => ({
    idle: { frames: [generatePixelArt(idleAscii)], fps },
    attack: { frames: [generatePixelArt(attackAscii)], fps },
    gridSize: 16
});

// Direction Vectors
export const DIRECTION_VECTORS: Record<AttackDirection, {x: number, y: number}> = {
    'RIGHT': { x: 1, y: 0 },
    'LEFT': { x: -1, y: 0 },
    'UP': { x: 0, y: -1 },
    'DOWN': { x: 0, y: 1 },
    'UP_RIGHT': { x: 0.7, y: -0.7 },
    'DOWN_RIGHT': { x: 0.7, y: 0.7 },
    'UP_LEFT': { x: -0.7, y: -0.7 },
    'DOWN_LEFT': { x: -0.7, y: 0.7 }
};

export const INITIAL_PLANT_STATS: Record<string, PlantConfig> = {
  [BasePlantType.SUNFLOWER]: { 
      type: BasePlantType.SUNFLOWER, name: 'Sunflower', cost: 50, cooldown: 5000, health: 300, icon: '🌻', description: 'Produces sun',
      visuals: createVisuals(ART_SUNFLOWER)
  },
  [BasePlantType.PEASHOOTER]: { 
      type: BasePlantType.PEASHOOTER, name: 'Peashooter', cost: 100, cooldown: 5000, health: 300, icon: '🌱', description: 'Shoots peas',
      visuals: createVisuals(ART_PEASHOOTER)
  },
  [BasePlantType.WALLNUT]: { 
      type: BasePlantType.WALLNUT, name: 'Wall-nut', cost: 50, cooldown: 20000, health: 4000, icon: '🥔', description: 'Blocks zombies',
      visuals: createVisuals(ART_WALLNUT)
  },
  [BasePlantType.CHERRY_BOMB]: { 
      type: BasePlantType.CHERRY_BOMB, name: 'Cherry Bomb', cost: 150, cooldown: 30000, health: 10000, icon: '🍒', description: 'Explodes area',
      visuals: createVisuals(ART_CHERRY_BOMB)
  },
  
  [BasePlantType.POTATO_MINE]: { 
      type: BasePlantType.POTATO_MINE, name: 'Potato Mine', cost: 25, cooldown: 30000, health: 300, icon: '🥔💥', description: 'Explodes on contact',
      visuals: createVisuals(ART_POTATO_MINE)
  },
  [BasePlantType.SNOW_PEA]: { 
      type: BasePlantType.SNOW_PEA, name: 'Snow Pea', cost: 175, cooldown: 5000, health: 300, icon: '❄️', description: 'Shoots frozen peas',
      visuals: createVisuals(ART_SNOW_PEA)
  },
  [BasePlantType.CHOMPER]: { 
      type: BasePlantType.CHOMPER, name: 'Chomper', cost: 150, cooldown: 7500, health: 300, icon: '🍖', description: 'Devours a zombie',
      visuals: createVisuals(ART_CHOMPER)
  },
  [BasePlantType.REPEATER]: { 
      type: BasePlantType.REPEATER, name: 'Repeater', cost: 200, cooldown: 5000, health: 300, icon: '🌿', description: 'Shoots 2 peas',
      visuals: createVisuals(ART_REPEATER)
  },
  [BasePlantType.PUFF_SHROOM]: { 
      type: BasePlantType.PUFF_SHROOM, name: 'Puff-shroom', cost: 0, cooldown: 5000, health: 200, icon: '🍄', description: 'Short range shooter',
      visuals: createVisuals(ART_PUFF_SHROOM)
  },
  [BasePlantType.SUN_SHROOM]: { 
      type: BasePlantType.SUN_SHROOM, name: 'Sun-shroom', cost: 25, cooldown: 5000, health: 200, icon: '🟡', description: 'Small sun producer',
      visuals: createVisuals(ART_SUN_SHROOM)
  },
  [BasePlantType.FUME_SHROOM]: { 
      type: BasePlantType.FUME_SHROOM, name: 'Fume-shroom', cost: 75, cooldown: 5000, health: 300, icon: '💨', description: 'Shoots fumes',
      visuals: createVisuals(ART_FUME_SHROOM)
  },
  [BasePlantType.GRAVE_BUSTER]: { 
      type: BasePlantType.GRAVE_BUSTER, name: 'Grave Buster', cost: 75, cooldown: 5000, health: 300, icon: '🪦', description: 'Eats graves',
      visuals: createVisuals(ART_SQUASH)
  },
  [BasePlantType.HYPNO_SHROOM]: { 
      type: BasePlantType.HYPNO_SHROOM, name: 'Hypno-shroom', cost: 75, cooldown: 5000, health: 100, icon: '😵‍💫', description: 'Hypnotizes zombie',
      visuals: createVisuals(ART_PUFF_SHROOM) // Reuse puff for now
  },
  [BasePlantType.SCAREDY_SHROOM]: { 
      type: BasePlantType.SCAREDY_SHROOM, name: 'Scaredy-shroom', cost: 25, cooldown: 5000, health: 200, icon: '😨', description: 'Long range only',
      visuals: createVisuals(ART_PUFF_SHROOM)
  },
  [BasePlantType.ICE_SHROOM]: { 
      type: BasePlantType.ICE_SHROOM, name: 'Ice-shroom', cost: 75, cooldown: 30000, health: 100, icon: '🥶', description: 'Freezes all zombies',
      visuals: createVisuals(ART_SNOW_PEA)
  },
  [BasePlantType.DOOM_SHROOM]: { 
      type: BasePlantType.DOOM_SHROOM, name: 'Doom-shroom', cost: 125, cooldown: 30000, health: 100, icon: '💣', description: 'Massive boom',
      visuals: createVisuals(ART_CHERRY_BOMB) // Reuse bomb
  },
  [BasePlantType.SQUASH]: { 
      type: BasePlantType.SQUASH, name: 'Squash', cost: 50, cooldown: 30000, health: 10000, icon: '😠', description: 'Stomps zombies',
      visuals: createVisuals(ART_SQUASH)
  },
  [BasePlantType.JALAPENO]: { 
      type: BasePlantType.JALAPENO, name: 'Jalapeno', cost: 125, cooldown: 30000, health: 10000, icon: '🌶️', description: 'Destroys a lane',
      visuals: createVisuals(ART_JALAPENO)
  },
  [BasePlantType.SPIKEWEED]: { 
      type: BasePlantType.SPIKEWEED, name: 'Spikeweed', cost: 100, cooldown: 7500, health: 300, icon: '🌵', description: 'Damages walking zombies',
      visuals: createVisuals(ART_SPIKEWEED)
  },
  [BasePlantType.MELON_PULT]: { 
      type: BasePlantType.MELON_PULT, name: 'Melon-pult', cost: 300, cooldown: 7500, health: 300, icon: '🍉', description: 'Heavy splash damage',
      visuals: createVisuals(ART_MELON_PULT)
  },
  [BasePlantType.KERNEL_PULT]: { 
      type: BasePlantType.KERNEL_PULT, name: 'Kernel-pult', cost: 100, cooldown: 7500, health: 300, icon: '🌽', description: 'Shoots corn and butter',
      visuals: createVisuals(ART_KERNEL_PULT)
  },
  
  // New Plants
  [BasePlantType.TWIN_SUNFLOWER]: { 
      type: BasePlantType.TWIN_SUNFLOWER, name: 'Twin Sunflower', cost: 150, cooldown: 5000, health: 300, icon: '🌻🌻', description: 'Produces double sun',
      visuals: createVisuals(ART_SUNFLOWER)
  },
  [BasePlantType.THREEPEATER]: { 
      type: BasePlantType.THREEPEATER, name: 'Threepeater', cost: 325, cooldown: 7500, health: 300, icon: '🌲', description: 'Shoots in 3 lanes',
      visuals: createVisuals(ART_THREEPEATER)
  },
  [BasePlantType.GATLING_PEA]: { 
      type: BasePlantType.GATLING_PEA, name: 'Gatling Pea', cost: 250, cooldown: 5000, health: 300, icon: '☘️', description: 'Shoots 4 peas rapidly',
      visuals: createVisuals(ART_REPEATER)
  },
  [BasePlantType.TORCHWOOD]: { 
      type: BasePlantType.TORCHWOOD, name: 'Torchwood', cost: 175, cooldown: 7500, health: 300, icon: '🪵🔥', description: 'Ignites peas',
      visuals: createVisuals(ART_TORCHWOOD)
  },
  [BasePlantType.TALLNUT]: { 
      type: BasePlantType.TALLNUT, name: 'Tall-nut', cost: 125, cooldown: 30000, health: 8000, icon: '🥜⬆️', description: 'Very heavy defense',
      visuals: createVisuals(ART_TALLNUT)
  },
  // Huge Plant
  [BasePlantType.COB_CANNON]: { 
      type: BasePlantType.COB_CANNON, name: 'Cob Cannon', cost: 500, cooldown: 35000, health: 300, icon: '🌽💣', description: 'Click to launch massive cob',
      visuals: {
          idle: { frames: [generatePixelArt(ART_COB_CANNON)], fps: 5 },
          charging: { frames: [generatePixelArt(ART_COB_CANNON_CHARGING)], fps: 5 },
          gridSize: 16
      },
      visualScale: 1.1 // ADJUSTED
  },
  // Starfruit
  [BasePlantType.STARFRUIT]: {
      type: BasePlantType.STARFRUIT, name: 'Starfruit', cost: 125, cooldown: 7500, health: 300, icon: '⭐', description: 'Shoots stars in 5 directions',
      visuals: createVisuals(ART_STARFRUIT),
      attackDirections: ['UP', 'DOWN', 'LEFT', 'UP_RIGHT', 'DOWN_RIGHT'] // Classic PvZ Starfruit spread
  }
};

export const EFFECT_DURATIONS = {
  EXPLOSION: 800,
  DOOM_EXPLOSION: 1200,
  FIRE_ROW: 1500,
  FREEZE: 1000, 
  BUTTER_SPLAT: 500,
};

// Increased Speeds
export const INITIAL_ZOMBIE_STATS: Record<string, ZombieStatConfig> = {
  [BaseZombieType.NORMAL]: { 
      health: 200, speed: 0.05, damage: 1, icon: '🧟',
      visuals: createZombieVisuals(ART_ZOMBIE, ART_ZOMBIE),
      visualScale: 1.0
  }, 
  [BaseZombieType.CONEHEAD]: { 
      health: 560, speed: 0.05, damage: 1, icon: '🧟‍♂️',
      visuals: createZombieVisuals(ART_CONEHEAD, ART_CONEHEAD),
      visualScale: 1.0
  },
  [BaseZombieType.BUCKETHEAD]: { 
      health: 1300, speed: 0.05, damage: 1, icon: '👺',
      visuals: createZombieVisuals(ART_BUCKETHEAD, ART_BUCKETHEAD),
      visualScale: 1.0
  },
  
  [BaseZombieType.FOOTBALL]: { 
      health: 1400, speed: 0.12, damage: 1, icon: '🏈',
      visuals: createZombieVisuals(ART_FOOTBALL, ART_FOOTBALL),
      visualScale: 1.0
  }, 
  [BaseZombieType.NEWSPAPER]: { 
      health: 400, speed: 0.03, damage: 1, icon: '📰',
      visuals: createZombieVisuals(ART_NEWSPAPER, ART_NEWSPAPER),
      visualScale: 1.0
  }, 
  [BaseZombieType.SCREEN_DOOR]: { 
      health: 1000, speed: 0.05, damage: 1, icon: '🚪',
      visuals: createZombieVisuals(ART_SCREEN_DOOR, ART_SCREEN_DOOR),
      visualScale: 1.0
  },
  // --- NEW ADVANCED ZOMBIES ---
  [BaseZombieType.IMP]: {
      health: 100, speed: 0.08, damage: 1, icon: '👶',
      visuals: createZombieVisuals(ART_IMP, ART_IMP),
      visualScale: 0.7
  },
  [BaseZombieType.GARGANTUAR]: {
      health: 3000, speed: 0.03, damage: 50, icon: '👹',
      visuals: createZombieVisuals(ART_GARGANTUAR, ART_GARGANTUAR),
      visualScale: 1.5 // ADJUSTED
  },
  [BaseZombieType.MECH_BOSS]: {
      health: 6000, speed: 0.015, damage: 100, icon: '🤖',
      visuals: createZombieVisuals(ART_MECH_BOSS, ART_MECH_BOSS),
      visualScale: 1.6 // ADJUSTED
  }
};

export const PROJECTILE_SPEED = 0.7; 
export const CLEANER_SPEED = 0.8; 
export const PROJECTILE_DAMAGE = 20;
export const MELON_DAMAGE = 80;
export const KERNEL_DAMAGE = 20;
export const BUTTER_DAMAGE = 40;
export const COB_DAMAGE = 1800; // Massive damage

// Intervals
export const SUN_GENERATION_INTERVAL = 8000;
export const NATURAL_SUN_INTERVAL = 8000; 
export const WAVE_INTERVAL = 25000; 

const INITIAL_LEVELS: LevelConfig[] = [
    { 
        id: 1, 
        name: "Level 1-1", 
        mode: 'CLASSIC',
        scene: LevelScene.LAWN_DAY,
        totalWaves: 5, 
        startingSun: 150,
        enabledZombies: [BaseZombieType.NORMAL],
        spawnIntervalMultiplier: 1.2,
        difficulty: 1,
        seedSlots: 4,
        unlocksPlant: BasePlantType.SUNFLOWER
    },
    { 
        id: 2, 
        name: "Level 1-2", 
        mode: 'CLASSIC',
        scene: LevelScene.LAWN_DAY,
        totalWaves: 8, 
        startingSun: 200,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD],
        spawnIntervalMultiplier: 1.0,
        difficulty: 2,
        seedSlots: 5,
        unlocksPlant: BasePlantType.WALLNUT
    },
    { 
        id: 3, 
        name: "Level 1-3", 
        mode: 'CLASSIC',
        scene: LevelScene.LAWN_DAY,
        totalWaves: 10, 
        startingSun: 250,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD],
        spawnIntervalMultiplier: 0.9,
        difficulty: 3,
        seedSlots: 6,
        unlocksPlant: BasePlantType.POTATO_MINE
    },
    { 
        id: 4, 
        name: "Level 1-4", 
        mode: 'CLASSIC',
        scene: LevelScene.LAWN_DAY,
        totalWaves: 12, 
        startingSun: 300,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD, BaseZombieType.BUCKETHEAD],
        spawnIntervalMultiplier: 0.85,
        difficulty: 4,
        seedSlots: 6,
        unlocksPlant: BasePlantType.SNOW_PEA
    },
    {
        id: 5,
        name: "Level 2-1 (Night)",
        mode: 'CLASSIC',
        scene: LevelScene.LAWN_NIGHT,
        totalWaves: 12, 
        startingSun: 150,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.SCREEN_DOOR, BaseZombieType.NEWSPAPER],
        spawnIntervalMultiplier: 0.9,
        difficulty: 5,
        seedSlots: 7,
        unlocksPlant: BasePlantType.CHERRY_BOMB
    },
    {
        id: 6,
        name: "Level 2-5",
        mode: 'CLASSIC',
        scene: LevelScene.GRAVEYARD,
        totalWaves: 15,
        startingSun: 500,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.FOOTBALL, BaseZombieType.BUCKETHEAD],
        spawnIntervalMultiplier: 0.8,
        difficulty: 6,
        seedSlots: 7,
        unlocksPlant: BasePlantType.REPEATER
    },
    {
        id: 7,
        name: "Level 3-1",
        mode: 'CLASSIC',
        scene: LevelScene.BALCONY,
        totalWaves: 18,
        startingSun: 500,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.IMP, BaseZombieType.GARGANTUAR],
        spawnIntervalMultiplier: 0.75,
        difficulty: 7,
        seedSlots: 8,
        unlocksPlant: BasePlantType.TORCHWOOD
    },
    {
        id: 8,
        name: "Level 3-5",
        mode: 'CLASSIC',
        scene: LevelScene.FACTORY,
        totalWaves: 20,
        startingSun: 600,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.FOOTBALL, BaseZombieType.GARGANTUAR, BaseZombieType.MECH_BOSS],
        spawnIntervalMultiplier: 0.7,
        difficulty: 8,
        seedSlots: 8,
        unlocksPlant: BasePlantType.MELON_PULT
    },
    {
        id: 9,
        name: "Level 4-1 (Chaos)",
        mode: 'CLASSIC',
        scene: LevelScene.GRAVEYARD,
        totalWaves: 25,
        startingSun: 800,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.CONEHEAD, BaseZombieType.BUCKETHEAD, BaseZombieType.NEWSPAPER, BaseZombieType.FOOTBALL, BaseZombieType.SCREEN_DOOR],
        spawnIntervalMultiplier: 0.6,
        difficulty: 9,
        seedSlots: 9,
        unlocksPlant: BasePlantType.STARFRUIT
    },
    {
        id: 10,
        name: "Level 5-10 (BOSS)",
        mode: 'CLASSIC',
        scene: LevelScene.FACTORY,
        totalWaves: 15, // Dense waves
        startingSun: 1500,
        enabledZombies: [BaseZombieType.NORMAL, BaseZombieType.IMP, BaseZombieType.GARGANTUAR, BaseZombieType.MECH_BOSS],
        spawnIntervalMultiplier: 1.0,
        difficulty: 10,
        seedSlots: 10,
        unlocksPlant: BasePlantType.COB_CANNON
    }
];

// Mutable Exports
export const PLANT_STATS: Record<string, PlantConfig> = { ...INITIAL_PLANT_STATS };
export const ZOMBIE_STATS: Record<string, ZombieStatConfig> = { ...INITIAL_ZOMBIE_STATS };
export const LEVELS: LevelConfig[] = [ ...INITIAL_LEVELS ];

// Reset Function for DLC Toggling
export const RESTORE_CONSTANTS = () => {
    // Clear existing keys
    Object.keys(PLANT_STATS).forEach(key => delete PLANT_STATS[key]);
    Object.keys(ZOMBIE_STATS).forEach(key => delete ZOMBIE_STATS[key]);
    
    // Restore initials
    Object.assign(PLANT_STATS, INITIAL_PLANT_STATS);
    Object.assign(ZOMBIE_STATS, INITIAL_ZOMBIE_STATS);
    
    // Restore levels
    LEVELS.length = 0;
    LEVELS.push(...INITIAL_LEVELS);
};

// --- CONSUMABLES DEFINITION ---
export const CONSUMABLES: Record<ConsumableType, { name: string, icon: string, cost: number, description: string }> = {
    [ConsumableType.SUN_PACK]: { name: 'Sun Crate', icon: '☀️', cost: 1000, description: 'Instantly gives 500 Sun.' },
    [ConsumableType.REPAIR_KIT]: { name: 'Repair Kit', icon: '🔧', cost: 500, description: 'Fully heals all plants.' },
    [ConsumableType.TACTICAL_NUKE]: { name: 'Doom Nuke', icon: '☢️', cost: 2500, description: 'Kills all zombies on screen.' },
    [ConsumableType.TIME_FREEZE]: { name: 'Stopwatch', icon: '⏱️', cost: 1500, description: 'Freezes zombies for 10 seconds.' }
};